version: "3.8"
services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"  # Mappe le port 3307 de l'hôte au port 3306 du conteneur
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projetdb
    depends_on:
      - database
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/share/nginx/html

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
